spring:
  application:
    name: zuulservice
  profiles:
    active:
      default
  zipkin:
     baseUrl:  localhost:9411
  cloud:
    config:
      enabled: true

server:
  port: 5555

#S etting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

# Let Zuul server talk to Eureka server
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#
#
#  debug:
#    request: true
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**
