spring:
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost
  data:
    jpa:
      repositories:
         enabled: true

# security:
#   oauth2:
#    resource:
#       userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true                           # Register the IP of the service rather than the server name
  client:
    registerWithEureka: true                        # Register the service with Eureka
    fetchRegistry: true                             # Pull down a local copy of the registry
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    # Location of the Eureka Service

# #Setting logging levels
# logging:
#   level:
#     com.netflix: WARN
#     org.springframework.web: WARN
#     com.thoughtmechanix: DEBUG
